---
- name: update group1 server
  hosts: group1

  tasks:
  - name: Ensure directory created
    file:
      path: /home/centos/n1_dir
      state: directory

  - name: Ensure directory created
    file:
      path: /home/centos/n11_dir
      state: directory

- name: update group2 server
  hosts: group2

  tasks:
  - name: Ensure directory created
    file:
      path: /home/centos/g2_dir
      state: directory 

  - name: Ensure directory created
    file:
      path: /home/centos/g22_dir
      state: directory 
...                





















...   