---
- name: Deploy Ecomm App  on n2 server
  hosts: n2
  become: yes

  tasks:
  - name: Install git
    yum:
      name: httpd
      state: present

  - name: Deploy Code
    git:
      dest: var/www/html
      repo: https://github.com/ravi2krishna/ecomm.git
       
...