---
- name: Modify ports on Web servers
  hosts: n3
  become: yes
  vars:
     custom_port: 9090

  tasks:
  - name: Copy Dynamic Config
    template:
      src: httpd.j2
      dest: /etc/httpd/conf/info.html

  - name: Restart HTTPD
    service:
       name: httpd
       state: restarted
          
...